### ISSUE TITLE
WebService::Dropbox install problem.

### ISSUE THREAD

**Issue by mcbilek** [CpanelInc/backup-transport-dropbox#1]
Could you check it please? 

[root@1547odhuo ~]# sudo cpan WebService::Dropbox
CPAN: Storable loaded ok (v2.20)
Going to read '/home/.cpan/Metadata'
  Database was generated on Sun, 13 Nov 2016 23:41:02 GMT
CPAN: LWP::UserAgent loaded ok (v5.833)
CPAN: Time::HiRes loaded ok (v1.9721)
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/01mailrc.txt.gz
CPAN: YAML loaded ok (v1.18)
Going to read '/home/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//modules/02packages.details.txt.gz
Going to read '/home/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Thu, 09 Aug 2018 10:41:05 GMT
.............
  New CPAN.pm version (v2.16) available.
  [Currently running version is v1.9402]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.

...............................................................DONE
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//modules/03modlist.data.gz
Going to read '/home/.cpan/sources/modules/03modlist.data.gz'
DONE
Going to write /home/.cpan/Metadata
Running install for module 'WebService::Dropbox'
Running make for A/AS/ASKADNA/WebService-Dropbox-2.07.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/A/AS/ASKADNA/WebService-Dropbox-2.07.tar.gz
CPAN: Digest::SHA loaded ok (v5.47)
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/A/AS/ASKADNA/CHECKSUMS
Checksum for /home/.cpan/sources/authors/id/A/AS/ASKADNA/WebService-Dropbox-2.07.tar.gz ok
CPAN: Archive::Tar loaded ok (v1.58)
WebService-Dropbox-2.07/Build.PL
WebService-Dropbox-2.07/Changes
WebService-Dropbox-2.07/HOW_TO_DEVELOPMENT.md
WebService-Dropbox-2.07/LICENSE
WebService-Dropbox-2.07/META.json
WebService-Dropbox-2.07/README.md
WebService-Dropbox-2.07/cpanfile
WebService-Dropbox-2.07/example/cli/README.md
WebService-Dropbox-2.07/example/cli/app.pl
WebService-Dropbox-2.07/example/cli/cpanfile
WebService-Dropbox-2.07/example/cli/cpanfile.snapshot
WebService-Dropbox-2.07/example/mig/mig.pl
WebService-Dropbox-2.07/example/web/README.md
WebService-Dropbox-2.07/example/web/app.psgi
WebService-Dropbox-2.07/example/web/cpanfile
WebService-Dropbox-2.07/lib/WebService/Dropbox.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Auth.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Files.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Files/CopyReference.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Files/ListFolder.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Files/UploadSession.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/TokenFromOAuth1.pm
WebService-Dropbox-2.07/lib/WebService/Dropbox/Users.pm
WebService-Dropbox-2.07/minil.toml
WebService-Dropbox-2.07/t/00_compile.t
WebService-Dropbox-2.07/t/05_accessor.t
WebService-Dropbox-2.07/t/10_api.t
WebService-Dropbox-2.07/t/11_range.t
WebService-Dropbox-2.07/t/12_304.t
WebService-Dropbox-2.07/t/20_copy.t
WebService-Dropbox-2.07/t/30_list.t
WebService-Dropbox-2.07/t/40_save_url.t
WebService-Dropbox-2.07/t/sample.png
WebService-Dropbox-2.07/META.yml
WebService-Dropbox-2.07/MANIFEST
CPAN: File::Temp loaded ok (v0.22)
---- Unsatisfied dependencies detected during ----
----  ASKADNA/WebService-Dropbox-2.07.tar.gz  ----
    Module::Build::Tiny [build_requires]
Running make test
  Make had some problems, won't test
  Delayed until after prerequisites
Running make install
  Make had some problems, won't install
  Delayed until after prerequisites
Running install for module 'Module::Build::Tiny'
Running make for L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
Checksum for /home/.cpan/sources/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz ok
Module-Build-Tiny-0.039/
Module-Build-Tiny-0.039/INSTALL
Module-Build-Tiny-0.039/t/
Module-Build-Tiny-0.039/t/release-pod-syntax.t
Module-Build-Tiny-0.039/t/lib/
Module-Build-Tiny-0.039/t/lib/DistGen.pm
Module-Build-Tiny-0.039/t/simple.t
Module-Build-Tiny-0.039/t/00-compile.t
Module-Build-Tiny-0.039/Build.PL
Module-Build-Tiny-0.039/lib/
Module-Build-Tiny-0.039/lib/Module/
Module-Build-Tiny-0.039/lib/Module/Build/
Module-Build-Tiny-0.039/lib/Module/Build/Tiny.pm
Module-Build-Tiny-0.039/dist.ini
Module-Build-Tiny-0.039/LICENSE
Module-Build-Tiny-0.039/Todo
Module-Build-Tiny-0.039/META.json
Module-Build-Tiny-0.039/Changes
Module-Build-Tiny-0.039/MANIFEST
Module-Build-Tiny-0.039/META.yml
Module-Build-Tiny-0.039/README
---- Unsatisfied dependencies detected during ----
----   LEONT/Module-Build-Tiny-0.039.tar.gz   ----
    ExtUtils::Helpers [build_requires]
    ExtUtils::InstallPaths [build_requires]
    ExtUtils::Config [build_requires]
Running make test
  Make had some problems, won't test
  Delayed until after prerequisites
Running make install
  Make had some problems, won't install
  Delayed until after prerequisites
Running install for module 'ExtUtils::Helpers'
Running make for L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz
Checksum for /home/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz ok
ExtUtils-Helpers-0.026/
ExtUtils-Helpers-0.026/lib/
ExtUtils-Helpers-0.026/lib/ExtUtils/
ExtUtils-Helpers-0.026/lib/ExtUtils/Helpers/
ExtUtils-Helpers-0.026/lib/ExtUtils/Helpers/Windows.pm
ExtUtils-Helpers-0.026/lib/ExtUtils/Helpers/Unix.pm
ExtUtils-Helpers-0.026/lib/ExtUtils/Helpers/VMS.pm
ExtUtils-Helpers-0.026/lib/ExtUtils/Helpers.pm
ExtUtils-Helpers-0.026/xt/
ExtUtils-Helpers-0.026/xt/author/
ExtUtils-Helpers-0.026/xt/author/pod-coverage.t
ExtUtils-Helpers-0.026/xt/author/00-compile.t
ExtUtils-Helpers-0.026/xt/author/pod-syntax.t
ExtUtils-Helpers-0.026/Makefile.PL
ExtUtils-Helpers-0.026/META.json
ExtUtils-Helpers-0.026/t/
ExtUtils-Helpers-0.026/t/split_like_shell.t
ExtUtils-Helpers-0.026/t/make_executable.t
ExtUtils-Helpers-0.026/t/man_pagename.t
ExtUtils-Helpers-0.026/t/tilde.t
ExtUtils-Helpers-0.026/MANIFEST
ExtUtils-Helpers-0.026/META.yml
ExtUtils-Helpers-0.026/dist.ini
ExtUtils-Helpers-0.026/INSTALL
ExtUtils-Helpers-0.026/LICENSE
ExtUtils-Helpers-0.026/Changes
ExtUtils-Helpers-0.026/README

  CPAN.pm: Going to build L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for ExtUtils::Helpers
cp lib/ExtUtils/Helpers.pm blib/lib/ExtUtils/Helpers.pm
cp lib/ExtUtils/Helpers/Windows.pm blib/lib/ExtUtils/Helpers/Windows.pm
cp lib/ExtUtils/Helpers/VMS.pm blib/lib/ExtUtils/Helpers/VMS.pm
cp lib/ExtUtils/Helpers/Unix.pm blib/lib/ExtUtils/Helpers/Unix.pm
Manifying blib/man3/ExtUtils::Helpers::Windows.3pm
Manifying blib/man3/ExtUtils::Helpers.3pm
Manifying blib/man3/ExtUtils::Helpers::VMS.3pm
Manifying blib/man3/ExtUtils::Helpers::Unix.3pm
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/gmake -- OK
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/make_executable.t ... ok   
t/man_pagename.t ...... ok   
t/split_like_shell.t .. ok     
t/tilde.t ............. ok   
All tests successful.
Files=4, Tests=30,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.10 cusr  0.03 csys =  0.16 CPU)
Result: PASS
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/gmake test -- OK
Running make install
L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz is just needed temporarily during building or testing. Do you want to install it permanently? [yes] yes
Prepending /home/.cpan/build/ExtUtils-Helpers-0.026-c1sk4v/blib/arch /home/.cpan/build/ExtUtils-Helpers-0.026-c1sk4v/blib/lib to PERL5LIB for 'install'
Manifying blib/man3/ExtUtils::Helpers::Windows.3pm
Manifying blib/man3/ExtUtils::Helpers.3pm
Manifying blib/man3/ExtUtils::Helpers::VMS.3pm
Manifying blib/man3/ExtUtils::Helpers::Unix.3pm
Installing /usr/local/share/perl5/ExtUtils/Helpers.pm
Installing /usr/local/share/perl5/ExtUtils/Helpers/Unix.pm
Installing /usr/local/share/perl5/ExtUtils/Helpers/Windows.pm
Installing /usr/local/share/perl5/ExtUtils/Helpers/VMS.pm
Installing /usr/local/share/man/man3/ExtUtils::Helpers::Unix.3pm
Installing /usr/local/share/man/man3/ExtUtils::Helpers.3pm
Installing /usr/local/share/man/man3/ExtUtils::Helpers::VMS.3pm
Installing /usr/local/share/man/man3/ExtUtils::Helpers::Windows.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/gmake install UNINST=1 -- OK
Running install for module 'ExtUtils::InstallPaths'
Running make for L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/L/LE/LEONT/CHECKSUMS
Checksum for /home/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz ok
ExtUtils-InstallPaths-0.012/
ExtUtils-InstallPaths-0.012/lib/
ExtUtils-InstallPaths-0.012/lib/ExtUtils/
ExtUtils-InstallPaths-0.012/lib/ExtUtils/InstallPaths.pm
ExtUtils-InstallPaths-0.012/xt/
ExtUtils-InstallPaths-0.012/xt/author/
ExtUtils-InstallPaths-0.012/xt/author/pod-coverage.t
ExtUtils-InstallPaths-0.012/xt/author/pod-syntax.t
ExtUtils-InstallPaths-0.012/t/
ExtUtils-InstallPaths-0.012/t/destinations.t
ExtUtils-InstallPaths-0.012/Makefile.PL
ExtUtils-InstallPaths-0.012/META.json
ExtUtils-InstallPaths-0.012/MANIFEST
ExtUtils-InstallPaths-0.012/META.yml
ExtUtils-InstallPaths-0.012/dist.ini
ExtUtils-InstallPaths-0.012/INSTALL
ExtUtils-InstallPaths-0.012/LICENSE
ExtUtils-InstallPaths-0.012/Changes

  CPAN.pm: Going to build L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz

Checking if your kit is complete...
Looks good
Warning: prerequisite ExtUtils::Config 0.002 not found.
Writing Makefile for ExtUtils::InstallPaths
---- Unsatisfied dependencies detected during ----
---- LEONT/ExtUtils-InstallPaths-0.012.tar.gz ----
    ExtUtils::Config [requires]
Running make test
  Delayed until after prerequisites
Running make install
  Delayed until after prerequisites
Running install for module 'ExtUtils::Config'
Running make for L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
Fetching with LWP:
  http://mirror.funkfreundelandshut.de/cpan//authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
Checksum for /home/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz ok
ExtUtils-Config-0.008/
ExtUtils-Config-0.008/INSTALL
ExtUtils-Config-0.008/t/
ExtUtils-Config-0.008/t/release-pod-syntax.t
ExtUtils-Config-0.008/t/basics.t
ExtUtils-Config-0.008/t/release-pod-coverage.t
ExtUtils-Config-0.008/t/00-compile.t
ExtUtils-Config-0.008/Makefile.PL
ExtUtils-Config-0.008/lib/
ExtUtils-Config-0.008/lib/ExtUtils/
ExtUtils-Config-0.008/lib/ExtUtils/Config.pm
ExtUtils-Config-0.008/dist.ini
ExtUtils-Config-0.008/LICENSE
ExtUtils-Config-0.008/META.json
ExtUtils-Config-0.008/Changes
ExtUtils-Config-0.008/MANIFEST
ExtUtils-Config-0.008/META.yml
ExtUtils-Config-0.008/README

  CPAN.pm: Going to build L/LE/LEONT/ExtUtils-Config-0.008.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for ExtUtils::Config
cp lib/ExtUtils/Config.pm blib/lib/ExtUtils/Config.pm
Manifying blib/man3/ExtUtils::Config.3pm
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/gmake -- OK
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ............ ok   
t/basics.t ................ ok   
t/release-pod-coverage.t .. skipped: these tests are for release candidate testing
t/release-pod-syntax.t .... skipped: these tests are for release candidate testing
All tests successful.
Files=4, Tests=9,  0 wallclock secs ( 0.02 usr  0.02 sys +  0.17 cusr  0.02 csys =  0.23 CPU)
Result: PASS
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/gmake test -- OK
Running make install
L/LE/LEONT/ExtUtils-Config-0.008.tar.gz is just needed temporarily during building or testing. Do you want to install it permanently? [yes] yes
Prepending /home/.cpan/build/ExtUtils-Config-0.008-7lHQwv/blib/arch /home/.cpan/build/ExtUtils-Config-0.008-7lHQwv/blib/lib to PERL5LIB for 'install'
Installing /usr/local/share/perl5/ExtUtils/Config.pm
Installing /usr/local/share/man/man3/ExtUtils::Config.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/gmake install UNINST=1 -- OK
Running make for L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  Has already been unwrapped into directory /home/.cpan/build/ExtUtils-InstallPaths-0.012-xUuuuX

  CPAN.pm: Going to build L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz

cp lib/ExtUtils/InstallPaths.pm blib/lib/ExtUtils/InstallPaths.pm
Manifying blib/man3/ExtUtils::InstallPaths.3pm
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/gmake -- OK
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/destinations.t .. 1/111 cannot remove path when cwd is /tmp/EIP-D5RICQeC for /tmp/EIP-D5RICQeC:  at /usr/share/perl5/File/Temp.pm line 902
t/destinations.t .. ok       
All tests successful.
Files=1, Tests=111,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.06 cusr  0.00 csys =  0.08 CPU)
Result: PASS
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/gmake test -- OK
Running make install
L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz is just needed temporarily during building or testing. Do you want to install it permanently? [yes] yes
Prepending /home/.cpan/build/ExtUtils-InstallPaths-0.012-xUuuuX/blib/arch /home/.cpan/build/ExtUtils-InstallPaths-0.012-xUuuuX/blib/lib to PERL5LIB for 'install'
Installing /usr/local/share/perl5/ExtUtils/InstallPaths.pm
Installing /usr/local/share/man/man3/ExtUtils::InstallPaths.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/gmake install UNINST=1 -- OK
ExtUtils::Config is up to date (0.008).
Running make for L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz

  CPAN.pm: Going to build L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz

Parse::CPAN::Meta version 1.44 required--this is only version 1.40 at /usr/share/perl5/CPAN/Meta/Converter.pm line 28.
BEGIN failed--compilation aborted at /usr/share/perl5/CPAN/Meta/Converter.pm line 28.
Compilation failed in require at /usr/share/perl5/CPAN/Meta.pm line 59.
BEGIN failed--compilation aborted at /usr/share/perl5/CPAN/Meta.pm line 59.
Compilation failed in require at lib/Module/Build/Tiny.pm line 8.
BEGIN failed--compilation aborted at lib/Module/Build/Tiny.pm line 8.
Compilation failed in require at Build.PL line 3.
BEGIN failed--compilation aborted at Build.PL line 3.
No 'Build' created  LEONT/Module-Build-Tiny-0.039.tar.gz
  /usr/bin/perl Build.PL  -- NOT OK
Running Build test
  Make had some problems, won't test
Running Build install
  Make had some problems, won't install
Running make for A/AS/ASKADNA/WebService-Dropbox-2.07.tar.gz
Warning: Prerequisite 'Module::Build::Tiny => 0.035' for 'ASKADNA/WebService-Dropbox-2.07.tar.gz' failed when processing 'LEONT/Module-Build-Tiny-0.039.tar.gz' with 'writemakefile => NO -- No 'Build' created
'. Continuing, but chances to succeed are limited.

  CPAN.pm: Going to build A/AS/ASKADNA/WebService-Dropbox-2.07.tar.gz

**Can't locate Module/Build/Tiny.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Build.PL line 9.
BEGIN failed--compilation aborted at Build.PL line 9.
No 'Build' created  ASKADNA/WebService-Dropbox-2.07.tar.gz
  /usr/bin/perl Build.PL  -- NOT OK
Running Build test
  Make had some problems, won't test
Running Build install
  Make had some problems, won't install
CPAN: Module::Build loaded ok (v0.35)**

**Comment by cPWilliamL** [comment]
Hi,

I see you are already running as the root user. Do you still face issues when not passing 'sudo' while using root?

If you are still facing issues, could you try installing the packages \`_cpanel-perl-526-Module-Build-Tiny_' or \`_perl-Module-Build-Tiny_' via yum and see if it corrects your issue?

Thanks,

**Comment by mcbilek** [comment]
Thank you for your answer, i tried without sudo but sama problem, after i tried `cpanel-perl-526-Module-Build-Tiny' or `perl-Module-Build-Tiny' via yum but nothing to do... fallowing error. Thank you.

root@1547odhuo ~]# yum install cpanel-perl-526-Module-Build-Tiny
Loaded plugins: fastestmirror, security, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 185.85.238.50
 * cpanel-addons-production-feed: 185.85.238.50
 * base: mirror.hosting.com.tr
 * extras: mirror.hosting.com.tr
 * updates: mirror.hosting.com.tr
Nothing to do
[root@1547odhuo ~]# yum install perl-Module-Build-Tiny
Loaded plugins: fastestmirror, security, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 185.85.238.50
 * cpanel-addons-production-feed: 185.85.238.50
 * base: mirror.hosting.com.tr
 * extras: mirror.hosting.com.tr
 * updates: mirror.hosting.com.tr
No package perl-Module-Build-Tiny available.
Error: Nothing to do
[root@1547odhuo ~]#

**Comment by mcbilek** [comment]
Hi again, i installed App::ModuleBuildTiny (0.023) from cpanel Home »Software »Install a Perl Module

now everything is ok, thank you.

**Comment by cPWilliamL** [comment]
Glad to hear that! Thanks for reporting back.

**Comment by omarshamali** [comment]
> Hi again, i installed App::ModuleBuildTiny (0.023) from cpanel Home »Software »Install a Perl Module
> 
> now everything is ok, thank you.

Thank you, that solved my issue too.
