### ISSUE TITLE
TECH-667 - /tmp getting full

### ISSUE THREAD

**Issue by cPWilliamL** [CpanelInc/backup-transport-dropbox#10]
Hi @cPWilliamL ,

While I was testing the setup, I found that the custom dropbox transfer created large number of files of 4.1 MB on in tmp causing 2.5 Gb of /tmp getting full and causing several other issue because of that.

/tmp folder issue I noticed after configuring your last updated master branch. The tmp files could be the session files generated while transferring backup files, but there were no backup files transferred to dropbox.

Could you please check if it is the case on your setup as well.

Thank You

_Originally posted by @erojiraiya in https://github.com/CpanelInc/backup-transport-dropbox/issues/6#issuecomment-425059388_

**Comment by cPWilliamL** [comment]
Originally, I overlooked the fact that WebService::Dropbox provided a multipart/chunking upload, so I began writing it myself, only reading X bytes at a time directly from the backup file. Once I realized WebService::Dropbox provided a multipart/chunking upload, I sided with the cpan provided method. While comparing my chunking method vs the cpan modules, I did notice that WebService::Dropbox::Files::UploadSession::upload_session doesn't do it the same way, instead it throws the buffer into a new file.
```
     11 sub upload_session {
     12     my ($self, $path, $content, $optional_params, $limit) = @_;
     13
     14     $limit ||= 4 * 1024 * 1024; # A typical chunk is 4 MB
     15
     16     my $session_id;
     17     my $offset = 0;
     18
     19     my $commit_params = {
     20         path => $path,
     21         %{ $optional_params || {} },
     22     };
     23
     24     my $upload;
     25     $upload = sub {
     26         my $buf;
     27         my $total = 0;
     28         my $chunk = 1024;
     29         my $tmp = File::Temp->new;
     30         my $is_last;
     31         while (my $read = read($content, $buf, $chunk)) {
     32             $tmp->print($buf);
```

This is likely the issue. While it is upstream with cpan WebService::Dropbox, I will do my best to correct it here.

**Comment by erojiraiya** [comment]
@cPWilliamL 

Thank you for the great explanation. Now the large number of same size files make sense as you quoted the related script.

I am positive when these issues will be solved, this application will be widely popular among cpanel users.

Cheers.

**Comment by umairali** [comment]
Can you suggest any thing how to fix this issue.

**Comment by cPWilliamL** [comment]
I apologize in the delay here; I've finally gotten some time to work on this project. I've been working on rewriting the upload_session call for large file uploads, to remove the usage of /tmp; however, I am facing issues with the Dropbox API's required usage of offsets. Proposed changes for this are taking place in the development-TECH-667 branch. At this time, it's not functional; for some reason, the large file is uploaded without errors, but missing one chunk. As the development-TECH-667 branch stands now, the output is below for a large file test upload:
```
total:209715200
read:33554432
start remaining:176160768 offset:1
read:33554432
append remaining:142606336 offset:33554433
read:33554432
append remaining:109051904 offset:67108865
read:33554432
append remaining:75497472 offset:100663297
read:33554432
append remaining:41943040 offset:134217729
read:33554432
append remaining:8388608 offset:167772161
read:8388608
finish remaining:0 offset:167772161
```
The math looks good to me; however, it's one chunk short on Dropbox's side. I am still working to resolve this. Once done, it will be merged into the development branch, and once I have your feedback, master.

**Comment by cPWilliamL** [comment]
I've heard back from one user in a ticket that this has corrected the issue; this has been merged to master. I am now closing the case. If you continue to face this issue, please ensure you are using 1.03; otherwise, please open a new case.
