### ISSUE TITLE
Destination Folder inconsistency

### ISSUE THREAD

**Issue by MHCreations** [CpanelInc/backup-transport-dropbox#13]
Using version 1.03 of the Perl Script -- 

Issue was resolved. Found that the naming convention in WHM -->Backups set up was ambiguous. 

This can be deleted (I cant seem to delete issue )

**Comment by cPWilliamL** [comment]
I am actively working with the @MHCreations in a ticket. It appears custom modifications have been made to adjust the upload directory when this can actually be set in the transport configuration via WHM. Closing
