### ISSUE TITLE
CentOS 7.9 - Could not upload test file -  "error": {".tag": "missing_scope", "required_scope": "files.content.write"}

### ISSUE THREAD

**Issue by slavajacobson** [CpanelInc/backup-transport-dropbox#25]
Error: Validation for transport “dropbox” failed: Could not upload test file: 2021-12-03T15:16:28 [WebService::Dropbox] [ERROR] https://content.dropboxapi.com/2/files/upload {"path":"/cpanel-backup/validate.tmp-4125-1638562587.txt","mode":"overwrite"} -> [401] {"error_summary": "missing_scope/.", "error": {".tag": "missing_scope", "required_scope": "files.content.write"}} at /usr/local/share/perl5/WebService/Dropbox.pm line 184.

files.content.write and files.content.read are both checked in the Dropbox app.

Any ideas?

**Comment by beeSeen** [comment]
You need to generate the access token AFTER you change the permission. So regenerating the access token should solve your problem. Took me a couple of days to find out..

**Comment by slavajacobson** [comment]
Amazing, thanks!
